image: ubuntu

environment:
  SITE_REPO_TOKEN: 
    secure: 9J4+3PqRqzTDiC280JthRE4EVP8YqK67eEDJmyD+2s+j8H/R5TyrJJJNnpOejxCH

branches:
  only:
    - develop
    - feature/upgrade-to-jekyll-4
    
install:
- sh: sudo rm -rf /var/lib/apt/lists/*
- sh: sudo apt-get update
- sh: sudo apt-get -y install curl
- sh: \curl -L https://get.rvm.io | bash -s stable --ruby
- sh: rvm reload
- sh: rvm install ruby
- sh: gem install jekyll bundler

build_script:
- sh: cd src
- sh: bundle install
- sh: git config --global credential.helper "store --file ~/.git-credentials"
- ps: git config --global user.email $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
- ps: git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
- ps: Add-Content "~/.git-credentials" "https://$($env:SITE_REPO_TOKEN):x-oauth-basic@github.com"
- ps: git clone https://github.com/giacomelli/giacomelli.github.io.git _site
- sh: cd ..
- sh: ./generate-bundle.sh
- sh: cd src
- sh: bundle exec jekyll build
- sh: cp ../CNAME _site/CNAME
- ps: echo ".nojekyll" > _site/.nojekyll
- ps: | 
      cd _site
      echo "{ `"date`": `"$(Get-Date -Format g)`", `"branch`": `"$($env:APPVEYOR_REPO_BRANCH)`" }" > version.json
      git add .
      git commit -m "$($env:APPVEYOR_REPO_COMMIT_MESSAGE)"
      git push